### ISSUE TITLE
Slack連携

### ISSUE THREAD

**Issue by miyaoka** [trkw/trkw#19]
各個人でやればいいかな…(trkw)

**Comment by trkw** [comment]
このサイトのチャットツールについては少し考えたい。
この手のプロジェクトにSlackはベターだけど、オープンソースであれば、
下記のようなチャットツールでも良いと思われる。

https://gitter.im/
https://discordapp.com/

今後人数が増えたり、ログを残すという意味でも強力になってきそう。
まだ今回の話題とはそれるが自動inviteさせる仕組みを作るのも良いかもしれない。

一旦作ってみる

**Comment by trkw** [comment]
gitterについては、下記の通りバッジを作成したので、READMEに追記しました。
誰でも入れるようにした。各種インテグレーションはそのうち作ろう。

[![Gitter](https://badges.gitter.im/trkw/Lobby.svg)](https://gitter.im/trkw/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
