### ISSUE TITLE
炎上対策を考えておく

### ISSUE THREAD

**Issue by miyaoka** [trkw/trkw#22]
- 消せない（リポジトリごと消す）
- 履歴が残る

**Comment by trkw** [comment]
炎上した時にも耐えられるサーバ構成にする…

**Comment by trkw** [comment]
その時考えるということで、一旦クローズ。

**Comment by miyaoka** [comment]
炎上したら耐えられないほうが良いのでは？
![ネット炎上のイラスト](https://1.bp.blogspot.com/-Ugp8MNhFivY/U7O6wYXEnfI/AAAAAAAAiSI/znBeaNmxoKI/s400/internet_enjou.png)
