### ISSUE TITLE
サイトのロゴを作る

### ISSUE THREAD

**Issue by miyaoka** [trkw/trkw#25]

**Comment by miyaoka** [comment]
[chicken icon - Google 検索](https://www.google.co.jp/search?q=chicken++icon&num=100&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj-uoy71OrOAhWBwJQKHSP2AL8Q_AUICCgB&biw=1598&bih=850)
とりあえず鶏アイコン
Twitterも鳥だけど、ニワトリになると食材感もあって愛嬌がある気がします

![](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQyNjwfSi2fcjpRfmXStHSuS6N12uprbIDy3bPwn2d9aeE_CoLW)

![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR5XosnV27y8HSsNsy_ClGHk1TGtgFCGHxdthtRlQULvlTlIXIkXQ)
正面もいいかも

![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQmqGR5oSvMhx98L30h66EkN2AyE3ieA3Xc6whFkX5FhrX_BzGJ)

![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTCavkm_WOybs5UsVeNjaFWCa7D_RVodzTleFpE2Y5uq283Umhg)

![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS1JHwjjoDCrNt0O4Hiob6-MTwxPxngN8wxPxDBG6zMW1-PjD-hkg)

![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSC9ubu6Qoa6Vw8rP0ybo3qcLaPnvRbMXxZ506jzmfwofnQQbtQPQ)
TRKWってロゴいれるのもいいかも

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1qDhEX_X-JJBvcjOE2m4M-dJZizRlDqaVmYaW1O5c2q8_y3PQ_A)
卵つきもちょっとかわいい

**Comment by trkw** [comment]
おおー可愛い

**Comment by trkw** [comment]
# ドラフト

## 通常ロゴ

<img width="191" alt="2016-09-14 4 58 16" src="https://cloud.githubusercontent.com/assets/2557813/18489307/f7287dd2-7a37-11e6-9087-4735ba4a10b4.png">

## シンボル

<img width="68" alt="2016-09-14 4 58 21" src="https://cloud.githubusercontent.com/assets/2557813/18489323/05be17c6-7a38-11e6-8c3b-afee09b4e46f.png">
