### ISSUE TITLE
英字フォントのCSS調整を行う

### ISSUE THREAD

**Issue by trkw** [trkw/trkw#34]
Androidでの表示が醜い

**Comment by miyaoka** [comment]
デプロイしたら

> font-family: -apple-system, 'Helvetica Neue', 'Hiragino Kaku Gothic ProN', '游ゴシック Medium', 'メイリオ', meiryo, sans-serif;

が

> font-family: -apple-system,Helvetica Neue,Hiragino Kaku Gothic ProN,\\6E38\30B4\30B7\30C3\30AF Medium,\\30E1\30A4\30EA\30AA,meiryo,sans-serif;

になったけどちゃんと参照されるのかな？（要確認）

**Comment by trkw** [comment]
どうやら参照されているように見えるため問題ない。

**Comment by miyaoka** [comment]
問題ないっぽいのでclose
