### ISSUE TITLE
カバー画像（thumbnail）の運用について

### ISSUE THREAD

**Issue by trkw** [trkw/trkw#37]
カバー画像については、綺麗な画像の運用が好ましいと思う。
例えば、今回phenomic関連の記事では下記のような画像を用意してみた。

![phenmic](https://cloud.githubusercontent.com/assets/2557813/18188245/9a20e0e8-70eb-11e6-9095-36d65f393d8a.png)

サイズは2048 * 512で、retina対応の為、実際の表示は1024 * 256となる。
サムネイル用に画像を用意するかこれをトリミングして512 * 512(256 * 256)の物を利用するかなど。
とりあえず検討していきたい。

**Comment by trkw** [comment]
このイメージ自体、metaデータから取得してCSSBackgroundへ指定してしまえるようにすれば、２回目以降の記事を書く際に捗る気がする。

postsのassetsディレクトリ下に上記の様なファイルを運用していく方針で考えてみたい。

**Comment by miyaoka** [comment]
画像が設定されていない場合の表示エラーを修正する

**Comment by miyaoka** [comment]
とりあえずcover指定がない場合には要素を追加しないようにした。
defaultを設定するかどうかはまた後で考える。
