### ISSUE TITLE
前後記事の表示について

### ISSUE THREAD

**Issue by miyaoka** [trkw/trkw#46]
enhanceCollectionのoptionに`addSiblingReferences: true`をつけるとnextとpreviousが追加される

参考：[How to use Collections in Phenomic](https://phenomic.io/docs/usage/collections/) （ここにはsiblingのことは書いてないけど）

**Comment by trkw** [comment]
トップページの一部記事が見えなくなったから、恐らく、前後機能が欲しいところ。
