### ISSUE TITLE
JSのコンポーネントの単位とCSSのコンポーネントの単位って、1対1で対応するものではない

### ISSUE THREAD

**Issue by miyaoka** [trkw/trkw#53]
[Qiitaのスライドモードは、mizchiが勝手に作った！？─Incrementsの縛られない開発スタイルを聞いてみた | HTML5Experts.jp](https://html5experts.jp/miyuki-baba/20328/)

> 森下：前職でReactを使っていてたんですが、Reactアプリの中でCSSを書いていくことに対しては自分なりの意見を持っています。CSS Modules等のCSS in JS系ツールを触ってみたりしたんですけど、僕はJSのコンポーネントの単位とCSSのコンポーネントの単位って、1対1で対応するものではないと考えています。

> それはデザインの再利用する単位と機能の再利用する単位が異なるからで、よくあるcomponentsディレクトリ配下に、index.jsとindex.cssがあるみたいな構成は結構難しいのかなと思っています。

> CSS in JS系ツールは、CSSそのものやその設計手法にあまり詳しくない人が、なんとなくJSのコンポーネントの単位でスタイルの影響範囲を閉じたい、という場合は良いものだと思います。QiitaとQiita:TeamはHTMLのレンダリングを全てReactが行っているわけではないので、部分的にCSS in JSを導入するのもおかしいので使いたくないです。

> Shadow DOMでスタイルの影響範囲に抑られるのはいいことだと思ってますが、そもそも装飾と機能を合わせたものをコンポーネントとしていろんなところで再利用していこうという考え自体が僕にはイマイチ…。

そんな気はしてた

**Comment by trkw** [comment]
cssに詳しい人がコミットしやすい設計ってどんな感じなんだろうか。
私はこのreactの1:1の関係でいいと思ってたが、読んでみるとナルホドと思ってしまったわ。
